### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by sarah872** [WGLab/NanoMod#1]
When running the following command:
`python NanoMod.py Annotate --wrkBase1 fast5_files/ --Ref reference.fasta`

I am getting the following error message:
`/Users/user/bin/miniconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Segmentation fault: 11`

I tried to force reinstalling h5py by using `pip install --upgrade --force-reinstall h5py`, but this did not help.

**Comment by sarah872** [comment]
The reference fasta is a full genome, i.e. 4 Mbp.
At what step should a full log be outputted?

**Comment by liuqianhn** [comment]
Hi @sarah872 ,  I could not repeat your error. Could you please set "--outLevel" to 1 to see whether you can have more output? 4M bp fasta should be fine. 

If you did not redirect the output to a file, the output would be in your screen. Otherwise, the log would be in the file you redirected to.

**Comment by liuqianhn** [comment]
Hi @sarah872 , may I know how much memory do you have for the running?

**Comment by liuqianhn** [comment]
Hi @sarah872 , Thanks for your feedback. I had the same guess of the error as you. 

I think it might also be related to the memory. May I know how many threads do you use? By default, "--threads" is 12, which is large if you only have 8GB memory. If you used default "--threads", try to set "--threads" to 1 or 2 to see whether you have the same error.

**Comment by sarah872** [comment]
The problem still persists. 
Thanks @liuqianhn for all the support!

**Comment by liuqianhn** [comment]
Closed because it might be a h5py issue.
