### ISSUE TITLE
Example trial data available?

### ISSUE THREAD

**Issue by JiahuiWangGit** [WGLab/NanoMod#10]
Hi,

Do you have any trial data to play with?

Thanks,
Jiahui

**Comment by liuqianhn** [comment]
Hi @JiahuiWangGit , we do not have example data for downloading since Nanopore fast5 files are usually larger. You might contact the authors of other papers (such as https://www.biorxiv.org/content/10.1101/094672v2.article-info) to download their data to test NanoMod. Thank you.

**Comment by liuqianhn** [comment]
Hi @JiahuiWangGit , please note that *NanoMod* needs both a group of test data and a negative control as input. If you do not have negative control, I recommend using our new tool *DeepMod* for the methylation prediction.
