### ISSUE TITLE
albacore 1.0<version<v2.0

### ISSUE THREAD

**Issue by JiahuiWangGit** [WGLab/NanoMod#11]
Any chance you would have a copy of albacore 1.0<version<v2.0 that supports R9 chemistry? I am trying to basecall R9 chemistry nanopore reads using NanoMod but my current version of albacore (2.3.1) only supported R9.4+.

**Comment by kaichop** [comment]
You will need to contact nanopore to get their software tools.

**Comment by JiahuiWangGit** [comment]
Hi, thanks for reply. Nanopore said older versions of albacore have been retired and not available now. Since you were using R9 data in your paper, I wonder if you still keep the version of albacore and willing to share it. Or if you could provide the processed data for both native and control? I just want to run Nanmod to see if it is working on my system.

**Comment by liuqianhn** [comment]
We used data published by other groups. You might contact the authors of other papers such as Nanoraw to download both modified and control data.

**Comment by liuqianhn** [comment]
Closed due to no recent activities.
