### ISSUE TITLE
NanoMod detect reports error 

### ISSUE THREAD

**Issue by XINYAN2** [WGLab/NanoMod#13]
Hello, I met this kind of error message when using NanoMod detect: 
"Error not equal ('Chr1', '-') 15347777 T G [('T', 3), ('G', 3)] [('G', 5)]
Error not equal ('Chr1', '-') 15347778 T C [('C', 4), ('T', 2)] [('C', 5)]
Error not equal ('Chr1', '-') 15347779 T C [('A', 1), ('C', 3), ('T', 2)] [('C', 5)]
Error not equal ('Chr1', '-') 15347780 T C [('A', 1), ('C', 3), ('T', 2)] [('C', 5)]
Error not equal ('Chr1', '-') 15347782 G A [('A', 3), ('T', 2), ('G', 1)] [('A', 5)]
Error not equal ('Chr1', '-') 15347783 T G [('C', 1), ('T', 2), ('G', 3)] [('G', 5)]
........"
There is a bunch of these kind of errors. Because the program didn't stop. I'm wondering if this kind of error affect the final result?

**Comment by liuqianhn** [comment]
Hi @XINYAN2 , if there are such errors for very small fraction of fast5 files, it would not affect the final results, otherwise, the final results are not correct.

**Comment by XINYAN2** [comment]
Thanks for your reply, @liuqianhn . this kind of errors count less than 1%. So I think this might be ok. But i still want to know why this error happens. Any idea why this error happens? Is there some error with my fast5 or configuration that may generate this "not equal" error?

**Comment by liuqianhn** [comment]
@XINYAN2 , sorry for missing your last comment. I have no idea about this error now. 

I will close the issue since no recent activities. Feel free to re-open it if you are still interested in it. Thanks.
