### ISSUE TITLE
Insertion methylation level

### ISSUE THREAD

**Issue by Yeeok** [WGLab/NanoMod#15]
Hi,
Is there any way to detect DNA modifications of insertions (one type of  SVs) by using NanoMod ?
Or only DNA modification within reference genome regions can be detected?  

Thank you.

- Yeeok Kang -

**Comment by liuqianhn** [comment]
Hi @Yeeok, it is a good idea to detect DNA modifications for insertions, but this version of NanoMod only detects modifications for the positions in a reference genome.

**Comment by liuqianhn** [comment]
Closed due to no recent response. Feel free to reopen it if you need more help.
