### ISSUE TITLE
Methylation calling results issues

### ISSUE THREAD

**Issue by PanZiwei** [WGLab/NanoMod#17]
Hi,
Thank you for developing such a useful tool. I have several questions and would really appreciate it if you can help answer the questions below: 

1. What 5mC format can you detect? I found that you are using CpG and GCGC format for the training dataset,  does it mean your model can only detect C in CpG or GCGC, or C in other formats also?

2. Is it possible to provide the sequence around the targeted base in the final methylation calling results at read level or genome level?

Thank you so much for your help!

**Comment by liuqianhn** [comment]
@PanZiwei Thanks for being interested in our tool. 
1. This repository is for NanoMod, which takes 2 compared datasets as input and outputs modifications at any position. 
2. I assume that you were referring to DeepMod, which needs training data. For DeepMod, (i) many well-trained models are on CpG or GCGC motifs on older data, and I did not test them on other motifs, and thus it is unknown whether the well-trained models are working on other motifs. You might need train your own models if you are interested. (ii) The final output has a reference position, and it would be easy to have the sequence around the targeted base in the reference, but it is not straightforward to have the sequence from each read for this version. We can provide the aligned position of targeted bases in long reads in next version.

**Comment by PanZiwei** [comment]
@liuqianhn Thank you so much for your reply! I am extremely sorry that I mixed the GitHub page for DeepMod and NanoMod and raised the issue on the wrong page, I inferred DeepMod actually.
Thanks again for your anwers and I will close the issue.
Best,
Ziwei
