### ISSUE TITLE
No calculation performed with Annotate

### ISSUE THREAD

**Issue by hilasharim** [WGLab/NanoMod#2]
Hi,
I am trying to run Annotate on a directory containing fast5 files. There is no error message, but the command runs in 1 second, and it doesn't seem to be doing any computation.

This is the structure of the fast5 file:
![image](https://user-images.githubusercontent.com/20622004/37399403-460599ca-278a-11e8-87fc-37cba9ec1c4a.png)

where Basecall_1D_001 is the output from Albacore.

This is the command I am trying to run:
python NanoMod/bin/NanoMod.py Annotate --wrkBase1 ~/data/METHYLATION/albacore/methylation1/workspace/pass/barcode05 --Ref ~/data/refs/lambda_neb --basecall_1d Basecall_1D_001

And this is the output in stdout:
/home/ebensteinlab/software/nanomod/nanomod/local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
                  MinNumSignal: 4
                           Ref: /home/ebensteinlab/data/refs/lambda_neb
         Resegment_signal_wind: 4
                Resegment_wind: 4
                      alignStr: bwa
                   basecall_1d: Basecall_1D_001
              basecall_2strand: BaseCalled_template
              files_per_thread: 300
               kmer_model_file: None
                      outLevel: 2
                     recursive: 1
                       threads: 12
                      wrkBase1: /home/ebensteinlab/data/METHYLATION/albacore/methylation1/workspace/pass/barcode05
Error information for different fast5 files:
Resegment information for signal neighbors: 
Total consuming time 1

Any help is appreciated!

**Comment by liuqianhn** [comment]
Hi @hilasharim , may I know "~/data/refs/lambda_neb" is a fasta file or a prefix of a fasta file?

**Comment by hilasharim** [comment]
Thank you for the response.

It's a fasta file. I've aligned the reads to it with bwa mem.

**Comment by liuqianhn** [comment]
Hi @hilasharim , could you please set "--outLevel" to 0 and share me the output? The output might be large. Thanks.

**Comment by hilasharim** [comment]
command:
python NanoMod/bin/NanoMod.py Annotate --wrkBase1 ~/data/METHYLATION/albacore/methylation1/workspace/pass/barcode05 --Ref ~/data/refs/lambda_neb --basecall_1d Basecall_1D_001 --outLevel 0

output:

/home/ebensteinlab/software/nanomod/nanomod/local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
                  MinNumSignal: 4
                           Ref: /home/ebensteinlab/data/refs/lambda_neb
         Resegment_signal_wind: 4
                Resegment_wind: 4
                      alignStr: bwa
                   basecall_1d: Basecall_1D_001
              basecall_2strand: BaseCalled_template
              files_per_thread: 300
               kmer_model_file: None
                      outLevel: 0
                     recursive: 1
                       threads: 12
                      wrkBase1: /home/ebensteinlab/data/METHYLATION/albacore/methylation1/workspace/pass/barcode05
Error information for different fast5 files:
Resegment information for signal neighbors: 
Total consuming time 1

**Comment by liuqianhn** [comment]
Hi @hilasharim , it seems that the annotation process did not run. Are the fast5 files directly in the folder of "/home/ebensteinlab/data/METHYLATION/albacore/methylation1/workspace/pass/barcode05"  or in the subfolders of "/home/ebensteinlab/data/METHYLATION/albacore/methylation1/workspace/pass/barcode05". If the former case, please set "--recursive 0".

**Comment by hilasharim** [comment]
setting --recursive to 0 fixed it. Thank you so much!

Another question - I ran Albacore 2.0 on the data, which is not supported. However, we also saved the event detection data directly from MinKnow - it's in the fast5 file under 'EventDetection_000'.
When I direct the program to BaseCall_1D_000, it can't find the even data, since it's saved in a different location in the file.
Is there a way to direct the program to the event data? I would like to avoid re-running albacore.

Thank you!

**Comment by liuqianhn** [comment]
Hi @hilasharim , I cannot make NanoMod to support Albacore 2.0 in a short time. I will let you know once it is available. Thanks.

**Comment by liuqianhn** [comment]
Hi @hilasharim , NanoMod can support Albacore 2+ now.

**Comment by liuqianhn** [comment]
Closed due to no new activities. Feel free to re-open if there is any more issues.
