### ISSUE TITLE
whether the NanoMod detects DNA methylation

### ISSUE THREAD

**Issue by dareddragon** [WGLab/NanoMod#23]
Hi, 
 I have a few questions about ManoMod and hope you can help me with them. My research method requires the detection of both thymine analogs(BrdU Edu) and 6mA methylation on DNA strands. I notice that your software platform NanoMod has successful applications on thymine analogs detection, and I wonder whether NanoMod has been applied in 5mC, 6mA methylation research. 
 I tried to reach you via email but I didn't find any email posted on the WG lab website. Could you email me to discuss future details? Cheers
  I'm looking forward to hearing from you. 

Kind regards,

Percy  

a1817954@adelaide.edu.au / tj.zhang@siat.ac.cn

**Comment by kaichop** [comment]
Email was sent by Chris so issue is closed.

**Comment by kaichop** [comment]
Email was sent by Chris so issue is closed.
