### ISSUE TITLE
Segmentation fault 11 using Annotate

### ISSUE THREAD

**Issue by grahama7162** [WGLab/NanoMod#3]
Hi,
When I run Annotate on my fast5 files the only output I get is 'segmentation fault 11'. The command i'm using is: 'python NanoMod/bin/NanoMod.py Annotate --wrkBase1 ~/Documents/E4_wga_unzipped/oct18_ecoli/E4_wga/E4_WGA_fast5/  --Ref ~/Documents/E4_all.fasta' where '~/Documents/E4_wga_unzipped/oct18_ecoli/E4_wga/E4_WGA_fast5/' is the directory containing my fast5 files to be annotated and '~/Documents/E4_all.fasta' is my reference sequence. 

Any help would be appreciated, thanks!

**Comment by liuqianhn** [comment]
Hi @grahama7162 , Could you please check #1 to see why you have the similar issue. If yes, I am afraid that the issue was caused in h5py. If no, could you please provide more detail for me to understand where the error was from? Thanks.

**Comment by liuqianhn** [comment]
Closed due to no further response. Feel free to reopen it if you have more issues.
