### ISSUE TITLE
use of albacore version > 2.0

### ISSUE THREAD

**Issue by axgraf** [WGLab/NanoMod#5]
Hi,
I wanted to give NanoMod a try for my dataset, but we are currently using the Albacore version (v.2.1.0). Instead of recalling the data with an older version, I wanted to ask if there any plans to update NanoMod to use it on basecalled data with >v.2.0?
Thanks
Alex

**Comment by liuqianhn** [comment]
Hi @axgraf , according to my current schedule, I will try to update NanoMod to support Albacore v2.+ by the end of the first week of May.

**Comment by liuqianhn** [comment]
Hi @axgraf , NanoMod can support Albacore 2+ now. Sorry for delaying the schedule.

**Comment by liuqianhn** [comment]
Closed due to no new activities. Feel free to re-open if there is any more issues.
