### ISSUE TITLE
RNA base modification with nanomod

### ISSUE THREAD

**Issue by Huanle** [WGLab/NanoMod#6]
Dear authors, 
Will nanomod be able to detect RNA base modification?

Kind Regards,
Huanlee

**Comment by liuqianhn** [comment]
Hi @Huanle , I am afraid that NanoMod does not support modification detection of RNA bases now.

**Comment by Huanle** [comment]
Hi liuqian,
Thanks for letting me know that.

**Comment by liuqianhn** [comment]
Hi @Huanle , Thank you very much for your great suggestions. I will let you know if we finish the development of additional functions for RNA data. I cannot give you clear schedule for this now. Sorry.
