### ISSUE TITLE
print Error Message

### ISSUE THREAD

**Issue by sarah872** [WGLab/NanoMod#7]
I am getting the following error, no matter what commands I use:

      File "NanoMod/bin/NanoMod.py", line 139
        print ErrorMessage, '\n'
                         ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print ErrorMessage, '\n')?

**Comment by liuqianhn** [comment]
Hi @sarah872 , did you use python v3.+? The tool works with python 2.7 now.

**Comment by sarah872** [comment]
what rpy2 version should then be used? The latest only works with python >2

**Comment by liuqianhn** [comment]
I am using rpy2 v2.8.6 for testing the tool.

**Comment by sarah872** [comment]
got Nanomod working now by using a python2.7 virtual environment with rpy2==2.8.6 installed. Thanks!
