### ISSUE TITLE
make NanoMod compatible with albacore v2.+

### ISSUE THREAD

**Issue by kaichop** [WGLab/NanoMod#8]
Original NanoMod was designed for Albacore v1 and had difficulty handling basecalled data generated by Albacore v2.

**Comment by Vykintasj** [comment]
Dear developers,
do you plan to implement compatibility with Albacore V2.+? When could it be expected?
Best regards

**Comment by liuqianhn** [comment]
Hi @Vykintasj, thank your for being interested in our tool. The tool has already supported Albacore V2.+.
